/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.rm.interview;
	
import nc.vo.pub.*;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class InterviewVO extends SuperVO {
	private java.lang.String pk_interview;
	private java.lang.String pk_group;
	private java.lang.String pk_org;
	private java.lang.String pk_psndoc;
	private java.lang.Integer interviewstate;
	private nc.vo.pub.lang.UFBoolean isoffersended;
	private java.lang.String charger;
	private nc.vo.pub.lang.UFLiteralDate begindate;
	private nc.vo.pub.lang.UFLiteralDate enddate;
	private nc.vo.pub.lang.UFDateTime creationtime;
	private java.lang.String creator;
	private nc.vo.pub.lang.UFDateTime modifiedtime;
	private java.lang.String modifier;
	private nc.vo.pub.lang.UFBoolean isuse;
	private java.lang.String pk_reg_dept;
	private java.lang.String pk_reg_org;
	private nc.vo.pub.lang.UFBoolean ishire;
	private java.lang.String pk_psndoc_job;
	private java.lang.String pk_reg_job;
	private nc.vo.pub.lang.UFDouble writtenscore;
	private nc.vo.pub.lang.UFDouble socre;
	private nc.vo.pub.lang.UFDouble allroundscore;
	private java.lang.String testresult;
	private java.lang.String remarks;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_INTERVIEW = "pk_interview";
	public static final String PK_GROUP = "pk_group";
	public static final String PK_ORG = "pk_org";
	public static final String PK_PSNDOC = "pk_psndoc";
	public static final String INTERVIEWSTATE = "interviewstate";
	public static final String ISOFFERSENDED = "isoffersended";
	public static final String CHARGER = "charger";
	public static final String BEGINDATE = "begindate";
	public static final String ENDDATE = "enddate";
	public static final String CREATIONTIME = "creationtime";
	public static final String CREATOR = "creator";
	public static final String MODIFIEDTIME = "modifiedtime";
	public static final String MODIFIER = "modifier";
	public static final String ISUSE = "isuse";
	public static final String PK_REG_DEPT = "pk_reg_dept";
	public static final String PK_REG_ORG = "pk_reg_org";
	public static final String ISHIRE = "ishire";
	public static final String PK_PSNDOC_JOB = "pk_psndoc_job";
	public static final String PK_REG_JOB = "pk_reg_job";
	public static final String WRITTENSCORE = "writtenscore";
	public static final String SOCRE = "socre";
	public static final String ALLROUNDSCORE = "allroundscore";
	public static final String TESTRESULT = "testresult";
	public static final String REMARKS = "remarks";
			
	/**
	 * 属性pk_interview的Getter方法.属性名：面试管理主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_interview () {
		return pk_interview;
	}   
	/**
	 * 属性pk_interview的Setter方法.属性名：面试管理主键
	 * 创建日期:
	 * @param newPk_interview java.lang.String
	 */
	public void setPk_interview (java.lang.String newPk_interview ) {
	 	this.pk_interview = newPk_interview;
	} 	  
	/**
	 * 属性pk_group的Getter方法.属性名：所属集团
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group () {
		return pk_group;
	}   
	/**
	 * 属性pk_group的Setter方法.属性名：所属集团
	 * 创建日期:
	 * @param newPk_group java.lang.String
	 */
	public void setPk_group (java.lang.String newPk_group ) {
	 	this.pk_group = newPk_group;
	} 	  
	/**
	 * 属性pk_org的Getter方法.属性名：所属组织
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org () {
		return pk_org;
	}   
	/**
	 * 属性pk_org的Setter方法.属性名：所属组织
	 * 创建日期:
	 * @param newPk_org java.lang.String
	 */
	public void setPk_org (java.lang.String newPk_org ) {
	 	this.pk_org = newPk_org;
	} 	  
	/**
	 * 属性pk_psndoc的Getter方法.属性名：面试人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_psndoc () {
		return pk_psndoc;
	}   
	/**
	 * 属性pk_psndoc的Setter方法.属性名：面试人
	 * 创建日期:
	 * @param newPk_psndoc java.lang.String
	 */
	public void setPk_psndoc (java.lang.String newPk_psndoc ) {
	 	this.pk_psndoc = newPk_psndoc;
	} 	  
	/**
	 * 属性interviewstate的Getter方法.属性名：面试状态
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getInterviewstate () {
		return interviewstate;
	}   
	/**
	 * 属性interviewstate的Setter方法.属性名：面试状态
	 * 创建日期:
	 * @param newInterviewstate java.lang.Integer
	 */
	public void setInterviewstate (java.lang.Integer newInterviewstate ) {
	 	this.interviewstate = newInterviewstate;
	} 	  
	/**
	 * 属性isoffersended的Getter方法.属性名：已发送邀请函
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getIsoffersended () {
		return isoffersended;
	}   
	/**
	 * 属性isoffersended的Setter方法.属性名：已发送邀请函
	 * 创建日期:
	 * @param newIsoffersended nc.vo.pub.lang.UFBoolean
	 */
	public void setIsoffersended (nc.vo.pub.lang.UFBoolean newIsoffersended ) {
	 	this.isoffersended = newIsoffersended;
	} 	  
	/**
	 * 属性charger的Getter方法.属性名：面试负责人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCharger () {
		return charger;
	}   
	/**
	 * 属性charger的Setter方法.属性名：面试负责人
	 * 创建日期:
	 * @param newCharger java.lang.String
	 */
	public void setCharger (java.lang.String newCharger ) {
	 	this.charger = newCharger;
	} 	  
	/**
	 * 属性begindate的Getter方法.属性名：开始日期
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFLiteralDate
	 */
	public nc.vo.pub.lang.UFLiteralDate getBegindate () {
		return begindate;
	}   
	/**
	 * 属性begindate的Setter方法.属性名：开始日期
	 * 创建日期:
	 * @param newBegindate nc.vo.pub.lang.UFLiteralDate
	 */
	public void setBegindate (nc.vo.pub.lang.UFLiteralDate newBegindate ) {
	 	this.begindate = newBegindate;
	} 	  
	/**
	 * 属性enddate的Getter方法.属性名：结束日期
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFLiteralDate
	 */
	public nc.vo.pub.lang.UFLiteralDate getEnddate () {
		return enddate;
	}   
	/**
	 * 属性enddate的Setter方法.属性名：结束日期
	 * 创建日期:
	 * @param newEnddate nc.vo.pub.lang.UFLiteralDate
	 */
	public void setEnddate (nc.vo.pub.lang.UFLiteralDate newEnddate ) {
	 	this.enddate = newEnddate;
	} 	  
	/**
	 * 属性creationtime的Getter方法.属性名：创建时间
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getCreationtime () {
		return creationtime;
	}   
	/**
	 * 属性creationtime的Setter方法.属性名：创建时间
	 * 创建日期:
	 * @param newCreationtime nc.vo.pub.lang.UFDateTime
	 */
	public void setCreationtime (nc.vo.pub.lang.UFDateTime newCreationtime ) {
	 	this.creationtime = newCreationtime;
	} 	  
	/**
	 * 属性creator的Getter方法.属性名：创建人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCreator () {
		return creator;
	}   
	/**
	 * 属性creator的Setter方法.属性名：创建人
	 * 创建日期:
	 * @param newCreator java.lang.String
	 */
	public void setCreator (java.lang.String newCreator ) {
	 	this.creator = newCreator;
	} 	  
	/**
	 * 属性modifiedtime的Getter方法.属性名：最后修改时间
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getModifiedtime () {
		return modifiedtime;
	}   
	/**
	 * 属性modifiedtime的Setter方法.属性名：最后修改时间
	 * 创建日期:
	 * @param newModifiedtime nc.vo.pub.lang.UFDateTime
	 */
	public void setModifiedtime (nc.vo.pub.lang.UFDateTime newModifiedtime ) {
	 	this.modifiedtime = newModifiedtime;
	} 	  
	/**
	 * 属性modifier的Getter方法.属性名：最后修改人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getModifier () {
		return modifier;
	}   
	/**
	 * 属性modifier的Setter方法.属性名：最后修改人
	 * 创建日期:
	 * @param newModifier java.lang.String
	 */
	public void setModifier (java.lang.String newModifier ) {
	 	this.modifier = newModifier;
	} 	  
	/**
	 * 属性isuse的Getter方法.属性名：是否应用
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getIsuse () {
		return isuse;
	}   
	/**
	 * 属性isuse的Setter方法.属性名：是否应用
	 * 创建日期:
	 * @param newIsuse nc.vo.pub.lang.UFBoolean
	 */
	public void setIsuse (nc.vo.pub.lang.UFBoolean newIsuse ) {
	 	this.isuse = newIsuse;
	} 	  
	/**
	 * 属性pk_reg_dept的Getter方法.属性名：应聘部门
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_reg_dept () {
		return pk_reg_dept;
	}   
	/**
	 * 属性pk_reg_dept的Setter方法.属性名：应聘部门
	 * 创建日期:
	 * @param newPk_reg_dept java.lang.String
	 */
	public void setPk_reg_dept (java.lang.String newPk_reg_dept ) {
	 	this.pk_reg_dept = newPk_reg_dept;
	} 	  
	/**
	 * 属性pk_reg_org的Getter方法.属性名：应聘组织
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_reg_org () {
		return pk_reg_org;
	}   
	/**
	 * 属性pk_reg_org的Setter方法.属性名：应聘组织
	 * 创建日期:
	 * @param newPk_reg_org java.lang.String
	 */
	public void setPk_reg_org (java.lang.String newPk_reg_org ) {
	 	this.pk_reg_org = newPk_reg_org;
	} 	  
	/**
	 * 属性ishire的Getter方法.属性名：是否录用
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getIshire () {
		return ishire;
	}   
	/**
	 * 属性ishire的Setter方法.属性名：是否录用
	 * 创建日期:
	 * @param newIshire nc.vo.pub.lang.UFBoolean
	 */
	public void setIshire (nc.vo.pub.lang.UFBoolean newIshire ) {
	 	this.ishire = newIshire;
	} 	  
	/**
	 * 属性pk_psndoc_job的Getter方法.属性名：应聘职位
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_psndoc_job () {
		return pk_psndoc_job;
	}   
	/**
	 * 属性pk_psndoc_job的Setter方法.属性名：应聘职位
	 * 创建日期:
	 * @param newPk_psndoc_job java.lang.String
	 */
	public void setPk_psndoc_job (java.lang.String newPk_psndoc_job ) {
	 	this.pk_psndoc_job = newPk_psndoc_job;
	} 	  
	/**
	 * 属性pk_reg_job的Getter方法.属性名：职位发布主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_reg_job () {
		return pk_reg_job;
	}   
	/**
	 * 属性pk_reg_job的Setter方法.属性名：职位发布主键
	 * 创建日期:
	 * @param newPk_reg_job java.lang.String
	 */
	public void setPk_reg_job (java.lang.String newPk_reg_job ) {
	 	this.pk_reg_job = newPk_reg_job;
	} 	  
	/**
	 * 属性writtenscore的Getter方法.属性名：笔试成绩
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getWrittenscore () {
		return writtenscore;
	}   
	/**
	 * 属性writtenscore的Setter方法.属性名：笔试成绩
	 * 创建日期:
	 * @param newWrittenscore nc.vo.pub.lang.UFDouble
	 */
	public void setWrittenscore (nc.vo.pub.lang.UFDouble newWrittenscore ) {
	 	this.writtenscore = newWrittenscore;
	} 	  
	/**
	 * 属性socre的Getter方法.属性名：面试成绩
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getSocre () {
		return socre;
	}   
	/**
	 * 属性socre的Setter方法.属性名：面试成绩
	 * 创建日期:
	 * @param newSocre nc.vo.pub.lang.UFDouble
	 */
	public void setSocre (nc.vo.pub.lang.UFDouble newSocre ) {
	 	this.socre = newSocre;
	} 	  
	/**
	 * 属性allroundscore的Getter方法.属性名：综合成绩
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getAllroundscore () {
		return allroundscore;
	}   
	/**
	 * 属性allroundscore的Setter方法.属性名：综合成绩
	 * 创建日期:
	 * @param newAllroundscore nc.vo.pub.lang.UFDouble
	 */
	public void setAllroundscore (nc.vo.pub.lang.UFDouble newAllroundscore ) {
	 	this.allroundscore = newAllroundscore;
	} 	  
	/**
	 * 属性testresult的Getter方法.属性名：体检结果
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTestresult () {
		return testresult;
	}   
	/**
	 * 属性testresult的Setter方法.属性名：体检结果
	 * 创建日期:
	 * @param newTestresult java.lang.String
	 */
	public void setTestresult (java.lang.String newTestresult ) {
	 	this.testresult = newTestresult;
	} 	  
	/**
	 * 属性remarks的Getter方法.属性名：备注
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getRemarks () {
		return remarks;
	}   
	/**
	 * 属性remarks的Setter方法.属性名：备注
	 * 创建日期:
	 * @param newRemarks java.lang.String
	 */
	public void setRemarks (java.lang.String newRemarks ) {
	 	this.remarks = newRemarks;
	} 	  
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_interview";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "rm_interview";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "rm_interview";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public InterviewVO() {
		super();	
	}    
	
	@nc.vo.annotation.MDEntityInfo(beanFullclassName =  "nc.vo.rm.interview.InterviewVO" )
	public IVOMeta getMetaData() {
   		return null;
  	}
} 


